---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/redhat-developer-demos/hybrid-cloud.git"
    app.quarkus.io/build-timestamp: "2020-03-30 - 19:23:15 +0000"
    app.quarkus.io/commit-id: "2d21e21ba2145aebbdd7ffd805575a53635f791a"
  labels:
    app.kubernetes.io/name: "hybrid-cloud-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hybrid-cloud-frontend"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/redhat-developer-demos/hybrid-cloud.git"
    app.quarkus.io/build-timestamp: "2020-03-30 - 19:23:15 +0000"
    app.quarkus.io/commit-id: "2d21e21ba2145aebbdd7ffd805575a53635f791a"
  labels:
    app.kubernetes.io/name: "hybrid-cloud-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hybrid-cloud-frontend"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "hybrid-cloud-frontend"
    app.kubernetes.io/version: "1.0.0"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/redhat-developer-demos/hybrid-cloud.git"
    app.quarkus.io/build-timestamp: "2020-03-30 - 19:23:15 +0000"
    app.quarkus.io/commit-id: "2d21e21ba2145aebbdd7ffd805575a53635f791a"
  labels:
    app.kubernetes.io/name: "hybrid-cloud-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hybrid-cloud-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hybrid-cloud-frontend"
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "https://github.com/redhat-developer-demos/hybrid-cloud.git"
        app.quarkus.io/build-timestamp: "2020-03-30 - 19:23:15 +0000"
        app.quarkus.io/commit-id: "2d21e21ba2145aebbdd7ffd805575a53635f791a"
      labels:
        app.kubernetes.io/name: "hybrid-cloud-frontend"
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "quay.io/rhdevelopers/hybrid-cloud-frontend:1.0.0"
        imagePullPolicy: "IfNotPresent"
        name: "hybrid-cloud-frontend"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "hybrid-cloud-frontend"
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  labels:
    app.kubernetes.io/name: "hybrid-cloud-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hybrid-cloud-frontend"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: "hybrid-cloud-frontend"
                port:
                  number: 8080
            path: "/"
            pathType: Prefix