apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: "backapi"
  name: "backapi"
  annotations:
    skupper.io/proxy: "http"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "backapi"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "backapi"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: WORKER_CLOUD_ID
          value: CHANGEME     
        image: "docker.io/burrsutter/hybrid-cloud-backend:1.0.0"
        imagePullPolicy: "IfNotPresent"
        name: "backapi"
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m" # 1/4 core
          limits:
            memory: "200Mi"
            cpu: "500m" # 1/2 core        
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        livenessProbe:
          httpGet:
              port: 8080
              path: /api/alive
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:  
            path: /api/ready
            port: 8080
          periodSeconds: 3
