apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skupper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/burrsutter/gke-skupper.git
    targetRevision: HEAD  
    path: argocd-skupper/overlays/sydney
  destination:
    server: https://kubernetes.default.svc
    namespace: hybrid  